### ISSUE TITLE
Can't get some attributes on Google validated rich snippets

### ISSUE THREAD

**Issue by tomav** [saary/node-microdata-parser#1]
Hi,

The following URL :  
http://www.boulanger.fr/tablette_apple_ipad_mini_16go_wifi_blanc/p_65608_572316.htm?xtor=SEC-2669-GOO--S-[{keyword}]

Only returns :  

```
[{"type":"http://schema.org/WebPage","breadcrumb":"AccueilMicro &amp; MultimédiaTablette tactileToutes les tablettes tactiles"}]
```

[Google can see microdata](http://www.google.com/webmasters/tools/richsnippets?q=http%3A%2F%2Fwww.boulanger.fr%2Ftablette_apple_ipad_mini_16go_wifi_blanc%2Fp_65608_572316.htm%3Fxtor%3DSEC-2669-GOO--S-%5B%7Bkeyword%7D%5D) 

Any idea why price, priceCurrency and others are not returned ?

Thanks.

**Comment by tomav** [comment]
I found the problem.
It works with your GIT version, not when using npm install.

Now I have price / currency : 
`[{"type":"http://schema.org/WebPage","breadcrumb":"AccueilMicro &amp; MultimédiaTablette tactileToutes les tablettes tactiles","offers":{"type":"http://schema.org/Offer","price":"299.00","priceCurrency":"EUR"}}]`

But nothing about http://schema.org/product

**Comment by saary** [comment]
Hi,

Thanks, I’ll update the npm.

Saar.
